name: dojooo CI/CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # 1. 작업 디렉토리 이동
            cd ~/spring-dojooo/

            # 2. 기존 컨테이너 종료 및 삭제
            docker stop dojooo-container || true
            docker rm dojooo-container || true
            docker rmi dojooo-image || true

            # 3. 최신 코드 Pull (옵션: 로컬에서 git clone 대신 zip 배포도 가능)
            git pull origin develop 

            # 4. Spring Boot Docker 이미지 빌드
            docker build -t dojooo-image .

            # 5. 새 컨테이너 실행
            docker run -d --name dojooo-container -p 8080:8080 dojooo-image
